#!/bin/sh
#
# This script serves as a replacement pinentry program, used solely to select a
# different pinentry program at any time, since it isn't so easy to do with
# gpg-agent. :(

case "${PINENTRY_USER_DATA:-curses}" in
  gui|gtk)
    exec /usr/bin/pinentry-gtk-2 "$@"
    ;;

  cli|curses)
    exec /usr/bin/pinentry-curses "$@"
    ;;

  none|select)
    exit 1
    ;;

  *)
    exec /usr/bin/pinentry-"$PINENTRY_USER_DATA" "$@"
esac
