#!/bin/sh
#
# A script that takes a command and runs it when a given port is pinged with
# netcat. The program relies on socat for listening to traffic locally, and
# netcat or anything that is able to connect to the port and close the
# connection.
#
# It'll listen on the port specified in the PINGCMD_PORT environment variable,
# or on port 8989 if the variable is empty or not set.
#
# Dependencies: socat

portToListenOn="${PINGCMD_PORT:-8989}"

while socat - tcp4-listen:"$portToListenOn"; do
  "$@"
done
