#!/bin/sh
#
# Diplay a popup on top of all other panes spanning 65% in width and height and
# containing a short git log so one can easily "peek" at it. The popup window
# should close the moment the user quits the log screen.
#
# Should be invoked only from within a git working tree.
#
# Depends on: tmux, git

cd "$(tmux display-message -p -F '#{pane_current_path}')"

[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != true ] && \
  exec tmux display-message -d 1000 "Not in a Git repository!"

exec tmux display-popup -E -w 65% -h 65% -d '#{pane_current_path}' \
  git log --oneline --color --graph --decorate
